using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetCMS.DataAccess
{
	#region Tables Struct
	public partial struct Tables
	{
		
		public static readonly string Category = @"Category";
        
		public static readonly string CategoryDetail = @"Category_Detail";
        
		public static readonly string Menu = @"Menu";
        
		public static readonly string Permission = @"Permission";
        
		public static readonly string Post = @"Post";
        
		public static readonly string Role = @"Role";
        
		public static readonly string RoleMenuPermissionDetail = @"Role_Menu_Permission_Detail";
        
		public static readonly string UserRoleDetail = @"User_Role_Detail";
        
		public static readonly string User = @"Users";
        
	}
	#endregion
    #region Schemas
    public partial class Schemas {
		
		public static TableSchema.Table Category
		{
            get { return DataService.GetSchema("Category", "DataAcessProvider"); }
		}
        
		public static TableSchema.Table CategoryDetail
		{
            get { return DataService.GetSchema("Category_Detail", "DataAcessProvider"); }
		}
        
		public static TableSchema.Table Menu
		{
            get { return DataService.GetSchema("Menu", "DataAcessProvider"); }
		}
        
		public static TableSchema.Table Permission
		{
            get { return DataService.GetSchema("Permission", "DataAcessProvider"); }
		}
        
		public static TableSchema.Table Post
		{
            get { return DataService.GetSchema("Post", "DataAcessProvider"); }
		}
        
		public static TableSchema.Table Role
		{
            get { return DataService.GetSchema("Role", "DataAcessProvider"); }
		}
        
		public static TableSchema.Table RoleMenuPermissionDetail
		{
            get { return DataService.GetSchema("Role_Menu_Permission_Detail", "DataAcessProvider"); }
		}
        
		public static TableSchema.Table UserRoleDetail
		{
            get { return DataService.GetSchema("User_Role_Detail", "DataAcessProvider"); }
		}
        
		public static TableSchema.Table User
		{
            get { return DataService.GetSchema("Users", "DataAcessProvider"); }
		}
        
	
    }
    #endregion
    #region View Struct
    public partial struct Views 
    {
		
    }
    #endregion
    
    #region Query Factories
	public static partial class DB
	{
        public static DataProvider _provider = DataService.Providers["DataAcessProvider"];
        static ISubSonicRepository _repository;
        public static ISubSonicRepository Repository 
        {
            get 
            {
                if (_repository == null)
                    return new SubSonicRepository(_provider);
                return _repository; 
            }
            set { _repository = value; }
        }
        public static Select SelectAllColumnsFrom<T>() where T : RecordBase<T>, new()
	    {
            return Repository.SelectAllColumnsFrom<T>();
	    }
	    public static Select Select()
	    {
            return Repository.Select();
	    }
	    
		public static Select Select(params string[] columns)
		{
            return Repository.Select(columns);
        }
	    
		public static Select Select(params Aggregate[] aggregates)
		{
            return Repository.Select(aggregates);
        }
   
	    public static Update Update<T>() where T : RecordBase<T>, new()
	    {
            return Repository.Update<T>();
	    }
	    
	    public static Insert Insert()
	    {
            return Repository.Insert();
	    }
	    
	    public static Delete Delete()
	    {
            return Repository.Delete();
	    }
	    
	    public static InlineQuery Query()
	    {
            return Repository.Query();
	    }
	    	    
	    
	}
    #endregion
    
}
#region Databases
public partial struct Databases 
{
	
	public static readonly string DataAcessProvider = @"DataAcessProvider";
    
}
#endregion