using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetCMS.DataAccess
{
    /// <summary>
    /// Controller class for Group_People_Detail
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class GroupPeopleDetailController
    {
        // Preload our schema..
        GroupPeopleDetail thisSchemaLoad = new GroupPeopleDetail();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public GroupPeopleDetailCollection FetchAll()
        {
            GroupPeopleDetailCollection coll = new GroupPeopleDetailCollection();
            Query qry = new Query(GroupPeopleDetail.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public GroupPeopleDetailCollection FetchByID(object UserId)
        {
            GroupPeopleDetailCollection coll = new GroupPeopleDetailCollection().Where("UserId", UserId).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public GroupPeopleDetailCollection FetchByQuery(Query qry)
        {
            GroupPeopleDetailCollection coll = new GroupPeopleDetailCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object UserId)
        {
            return (GroupPeopleDetail.Delete(UserId) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object UserId)
        {
            return (GroupPeopleDetail.Destroy(UserId) == 1);
        }
        
        
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(int UserId,int GroupPeopleId)
        {
            Query qry = new Query(GroupPeopleDetail.Schema);
            qry.QueryType = QueryType.Delete;
            qry.AddWhere("UserId", UserId).AND("GroupPeopleId", GroupPeopleId);
            qry.Execute();
            return (true);
        }        
       
    	
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int UserId,int GroupPeopleId)
	    {
		    GroupPeopleDetail item = new GroupPeopleDetail();
		    
            item.UserId = UserId;
            
            item.GroupPeopleId = GroupPeopleId;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int UserId,int GroupPeopleId)
	    {
		    GroupPeopleDetail item = new GroupPeopleDetail();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.UserId = UserId;
				
			item.GroupPeopleId = GroupPeopleId;
				
	        item.Save(UserName);
	    }
    }
}
