using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetCMS.DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the Login class.
	/// </summary>
    [Serializable]
	public partial class LoginCollection : ActiveList<Login, LoginCollection>
	{	   
		public LoginCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>LoginCollection</returns>
		public LoginCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                Login o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Login table.
	/// </summary>
	[Serializable]
	public partial class Login : ActiveRecord<Login>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public Login()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public Login(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public Login(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public Login(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("Login", TableType.Table, DataService.GetInstance("DataAcessProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "Id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarUserId = new TableSchema.TableColumn(schema);
				colvarUserId.ColumnName = "UserId";
				colvarUserId.DataType = DbType.Int32;
				colvarUserId.MaxLength = 0;
				colvarUserId.AutoIncrement = false;
				colvarUserId.IsNullable = false;
				colvarUserId.IsPrimaryKey = false;
				colvarUserId.IsForeignKey = false;
				colvarUserId.IsReadOnly = false;
				colvarUserId.DefaultSetting = @"";
				colvarUserId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUserId);
				
				TableSchema.TableColumn colvarToken = new TableSchema.TableColumn(schema);
				colvarToken.ColumnName = "Token";
				colvarToken.DataType = DbType.Guid;
				colvarToken.MaxLength = 0;
				colvarToken.AutoIncrement = false;
				colvarToken.IsNullable = false;
				colvarToken.IsPrimaryKey = false;
				colvarToken.IsForeignKey = false;
				colvarToken.IsReadOnly = false;
				colvarToken.DefaultSetting = @"";
				colvarToken.ForeignKeyTableName = "";
				schema.Columns.Add(colvarToken);
				
				TableSchema.TableColumn colvarDateLogin = new TableSchema.TableColumn(schema);
				colvarDateLogin.ColumnName = "DateLogin";
				colvarDateLogin.DataType = DbType.DateTime;
				colvarDateLogin.MaxLength = 0;
				colvarDateLogin.AutoIncrement = false;
				colvarDateLogin.IsNullable = true;
				colvarDateLogin.IsPrimaryKey = false;
				colvarDateLogin.IsForeignKey = false;
				colvarDateLogin.IsReadOnly = false;
				
						colvarDateLogin.DefaultSetting = @"(getdate())";
				colvarDateLogin.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDateLogin);
				
				TableSchema.TableColumn colvarIsLogout = new TableSchema.TableColumn(schema);
				colvarIsLogout.ColumnName = "IsLogout";
				colvarIsLogout.DataType = DbType.Boolean;
				colvarIsLogout.MaxLength = 0;
				colvarIsLogout.AutoIncrement = false;
				colvarIsLogout.IsNullable = true;
				colvarIsLogout.IsPrimaryKey = false;
				colvarIsLogout.IsForeignKey = false;
				colvarIsLogout.IsReadOnly = false;
				
						colvarIsLogout.DefaultSetting = @"((0))";
				colvarIsLogout.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIsLogout);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DataAcessProvider"].AddSchema("Login",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("UserId")]
		[Bindable(true)]
		public int UserId 
		{
			get { return GetColumnValue<int>(Columns.UserId); }
			set { SetColumnValue(Columns.UserId, value); }
		}
		  
		[XmlAttribute("Token")]
		[Bindable(true)]
		public Guid Token 
		{
			get { return GetColumnValue<Guid>(Columns.Token); }
			set { SetColumnValue(Columns.Token, value); }
		}
		  
		[XmlAttribute("DateLogin")]
		[Bindable(true)]
		public DateTime? DateLogin 
		{
			get { return GetColumnValue<DateTime?>(Columns.DateLogin); }
			set { SetColumnValue(Columns.DateLogin, value); }
		}
		  
		[XmlAttribute("IsLogout")]
		[Bindable(true)]
		public bool? IsLogout 
		{
			get { return GetColumnValue<bool?>(Columns.IsLogout); }
			set { SetColumnValue(Columns.IsLogout, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int varUserId,Guid varToken,DateTime? varDateLogin,bool? varIsLogout)
		{
			Login item = new Login();
			
			item.UserId = varUserId;
			
			item.Token = varToken;
			
			item.DateLogin = varDateLogin;
			
			item.IsLogout = varIsLogout;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,int varUserId,Guid varToken,DateTime? varDateLogin,bool? varIsLogout)
		{
			Login item = new Login();
			
				item.Id = varId;
			
				item.UserId = varUserId;
			
				item.Token = varToken;
			
				item.DateLogin = varDateLogin;
			
				item.IsLogout = varIsLogout;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn UserIdColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn TokenColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn DateLoginColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn IsLogoutColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"Id";
			 public static string UserId = @"UserId";
			 public static string Token = @"Token";
			 public static string DateLogin = @"DateLogin";
			 public static string IsLogout = @"IsLogout";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
