using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetCMS.DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the RoleMenuPermissionDetail class.
	/// </summary>
    [Serializable]
	public partial class RoleMenuPermissionDetailCollection : ActiveList<RoleMenuPermissionDetail, RoleMenuPermissionDetailCollection>
	{	   
		public RoleMenuPermissionDetailCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>RoleMenuPermissionDetailCollection</returns>
		public RoleMenuPermissionDetailCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                RoleMenuPermissionDetail o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Role_Menu_Permission_Detail table.
	/// </summary>
	[Serializable]
	public partial class RoleMenuPermissionDetail : ActiveRecord<RoleMenuPermissionDetail>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public RoleMenuPermissionDetail()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public RoleMenuPermissionDetail(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public RoleMenuPermissionDetail(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public RoleMenuPermissionDetail(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("Role_Menu_Permission_Detail", TableType.Table, DataService.GetInstance("DataAcessProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "Id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarRoleId = new TableSchema.TableColumn(schema);
				colvarRoleId.ColumnName = "RoleId";
				colvarRoleId.DataType = DbType.Int32;
				colvarRoleId.MaxLength = 0;
				colvarRoleId.AutoIncrement = false;
				colvarRoleId.IsNullable = true;
				colvarRoleId.IsPrimaryKey = false;
				colvarRoleId.IsForeignKey = true;
				colvarRoleId.IsReadOnly = false;
				colvarRoleId.DefaultSetting = @"";
				
					colvarRoleId.ForeignKeyTableName = "Role";
				schema.Columns.Add(colvarRoleId);
				
				TableSchema.TableColumn colvarPermissionId = new TableSchema.TableColumn(schema);
				colvarPermissionId.ColumnName = "PermissionId";
				colvarPermissionId.DataType = DbType.Int32;
				colvarPermissionId.MaxLength = 0;
				colvarPermissionId.AutoIncrement = false;
				colvarPermissionId.IsNullable = true;
				colvarPermissionId.IsPrimaryKey = false;
				colvarPermissionId.IsForeignKey = true;
				colvarPermissionId.IsReadOnly = false;
				colvarPermissionId.DefaultSetting = @"";
				
					colvarPermissionId.ForeignKeyTableName = "Permission";
				schema.Columns.Add(colvarPermissionId);
				
				TableSchema.TableColumn colvarMenuId = new TableSchema.TableColumn(schema);
				colvarMenuId.ColumnName = "MenuId";
				colvarMenuId.DataType = DbType.Int32;
				colvarMenuId.MaxLength = 0;
				colvarMenuId.AutoIncrement = false;
				colvarMenuId.IsNullable = true;
				colvarMenuId.IsPrimaryKey = false;
				colvarMenuId.IsForeignKey = true;
				colvarMenuId.IsReadOnly = false;
				colvarMenuId.DefaultSetting = @"";
				
					colvarMenuId.ForeignKeyTableName = "Menu";
				schema.Columns.Add(colvarMenuId);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DataAcessProvider"].AddSchema("Role_Menu_Permission_Detail",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("RoleId")]
		[Bindable(true)]
		public int? RoleId 
		{
			get { return GetColumnValue<int?>(Columns.RoleId); }
			set { SetColumnValue(Columns.RoleId, value); }
		}
		  
		[XmlAttribute("PermissionId")]
		[Bindable(true)]
		public int? PermissionId 
		{
			get { return GetColumnValue<int?>(Columns.PermissionId); }
			set { SetColumnValue(Columns.PermissionId, value); }
		}
		  
		[XmlAttribute("MenuId")]
		[Bindable(true)]
		public int? MenuId 
		{
			get { return GetColumnValue<int?>(Columns.MenuId); }
			set { SetColumnValue(Columns.MenuId, value); }
		}
		
		#endregion
		
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a Menu ActiveRecord object related to this RoleMenuPermissionDetail
		/// 
		/// </summary>
		public SweetCMS.DataAccess.Menu Menu
		{
			get { return SweetCMS.DataAccess.Menu.FetchByID(this.MenuId); }
			set { SetColumnValue("MenuId", value.Id); }
		}
		
		
		/// <summary>
		/// Returns a Permission ActiveRecord object related to this RoleMenuPermissionDetail
		/// 
		/// </summary>
		public SweetCMS.DataAccess.Permission Permission
		{
			get { return SweetCMS.DataAccess.Permission.FetchByID(this.PermissionId); }
			set { SetColumnValue("PermissionId", value.Id); }
		}
		
		
		/// <summary>
		/// Returns a Role ActiveRecord object related to this RoleMenuPermissionDetail
		/// 
		/// </summary>
		public SweetCMS.DataAccess.Role Role
		{
			get { return SweetCMS.DataAccess.Role.FetchByID(this.RoleId); }
			set { SetColumnValue("RoleId", value.Id); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int? varRoleId,int? varPermissionId,int? varMenuId)
		{
			RoleMenuPermissionDetail item = new RoleMenuPermissionDetail();
			
			item.RoleId = varRoleId;
			
			item.PermissionId = varPermissionId;
			
			item.MenuId = varMenuId;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,int? varRoleId,int? varPermissionId,int? varMenuId)
		{
			RoleMenuPermissionDetail item = new RoleMenuPermissionDetail();
			
				item.Id = varId;
			
				item.RoleId = varRoleId;
			
				item.PermissionId = varPermissionId;
			
				item.MenuId = varMenuId;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn RoleIdColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn PermissionIdColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn MenuIdColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"Id";
			 public static string RoleId = @"RoleId";
			 public static string PermissionId = @"PermissionId";
			 public static string MenuId = @"MenuId";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
