using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetCMS.DataAccess
{
    /// <summary>
    /// Controller class for Role_Menu_Permission_Detail
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class RoleMenuPermissionDetailController
    {
        // Preload our schema..
        RoleMenuPermissionDetail thisSchemaLoad = new RoleMenuPermissionDetail();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public RoleMenuPermissionDetailCollection FetchAll()
        {
            RoleMenuPermissionDetailCollection coll = new RoleMenuPermissionDetailCollection();
            Query qry = new Query(RoleMenuPermissionDetail.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public RoleMenuPermissionDetailCollection FetchByID(object Id)
        {
            RoleMenuPermissionDetailCollection coll = new RoleMenuPermissionDetailCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public RoleMenuPermissionDetailCollection FetchByQuery(Query qry)
        {
            RoleMenuPermissionDetailCollection coll = new RoleMenuPermissionDetailCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (RoleMenuPermissionDetail.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (RoleMenuPermissionDetail.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public RoleMenuPermissionDetail Insert(RoleMenuPermissionDetail roleMenuPermissionDetail)
	    {
            roleMenuPermissionDetail.Save(UserName);
            return roleMenuPermissionDetail;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int? RoleId,int? PermissionId,int? MenuId)
	    {
		    RoleMenuPermissionDetail item = new RoleMenuPermissionDetail();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.RoleId = RoleId;
				
			item.PermissionId = PermissionId;
				
			item.MenuId = MenuId;
				
	        item.Save(UserName);
	    }
    }
}
