using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetCMS.DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the GroupPeopleDetail class.
	/// </summary>
    [Serializable]
	public partial class GroupPeopleDetailCollection : ActiveList<GroupPeopleDetail, GroupPeopleDetailCollection>
	{	   
		public GroupPeopleDetailCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>GroupPeopleDetailCollection</returns>
		public GroupPeopleDetailCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                GroupPeopleDetail o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Group_People_Detail table.
	/// </summary>
	[Serializable]
	public partial class GroupPeopleDetail : ActiveRecord<GroupPeopleDetail>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public GroupPeopleDetail()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public GroupPeopleDetail(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public GroupPeopleDetail(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public GroupPeopleDetail(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("Group_People_Detail", TableType.Table, DataService.GetInstance("DataAcessProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarUserId = new TableSchema.TableColumn(schema);
				colvarUserId.ColumnName = "UserId";
				colvarUserId.DataType = DbType.Int32;
				colvarUserId.MaxLength = 0;
				colvarUserId.AutoIncrement = false;
				colvarUserId.IsNullable = false;
				colvarUserId.IsPrimaryKey = true;
				colvarUserId.IsForeignKey = true;
				colvarUserId.IsReadOnly = false;
				colvarUserId.DefaultSetting = @"";
				
					colvarUserId.ForeignKeyTableName = "Users";
				schema.Columns.Add(colvarUserId);
				
				TableSchema.TableColumn colvarGroupPeopleId = new TableSchema.TableColumn(schema);
				colvarGroupPeopleId.ColumnName = "GroupPeopleId";
				colvarGroupPeopleId.DataType = DbType.Int32;
				colvarGroupPeopleId.MaxLength = 0;
				colvarGroupPeopleId.AutoIncrement = false;
				colvarGroupPeopleId.IsNullable = false;
				colvarGroupPeopleId.IsPrimaryKey = true;
				colvarGroupPeopleId.IsForeignKey = true;
				colvarGroupPeopleId.IsReadOnly = false;
				colvarGroupPeopleId.DefaultSetting = @"";
				
					colvarGroupPeopleId.ForeignKeyTableName = "Group_People";
				schema.Columns.Add(colvarGroupPeopleId);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DataAcessProvider"].AddSchema("Group_People_Detail",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("UserId")]
		[Bindable(true)]
		public int UserId 
		{
			get { return GetColumnValue<int>(Columns.UserId); }
			set { SetColumnValue(Columns.UserId, value); }
		}
		  
		[XmlAttribute("GroupPeopleId")]
		[Bindable(true)]
		public int GroupPeopleId 
		{
			get { return GetColumnValue<int>(Columns.GroupPeopleId); }
			set { SetColumnValue(Columns.GroupPeopleId, value); }
		}
		
		#endregion
		
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a GroupPerson ActiveRecord object related to this GroupPeopleDetail
		/// 
		/// </summary>
		public SweetCMS.DataAccess.GroupPerson GroupPerson
		{
			get { return SweetCMS.DataAccess.GroupPerson.FetchByID(this.GroupPeopleId); }
			set { SetColumnValue("GroupPeopleId", value.Id); }
		}
		
		
		/// <summary>
		/// Returns a User ActiveRecord object related to this GroupPeopleDetail
		/// 
		/// </summary>
		public SweetCMS.DataAccess.User User
		{
			get { return SweetCMS.DataAccess.User.FetchByID(this.UserId); }
			set { SetColumnValue("UserId", value.Id); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int varUserId,int varGroupPeopleId)
		{
			GroupPeopleDetail item = new GroupPeopleDetail();
			
			item.UserId = varUserId;
			
			item.GroupPeopleId = varGroupPeopleId;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varUserId,int varGroupPeopleId)
		{
			GroupPeopleDetail item = new GroupPeopleDetail();
			
				item.UserId = varUserId;
			
				item.GroupPeopleId = varGroupPeopleId;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn UserIdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn GroupPeopleIdColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string UserId = @"UserId";
			 public static string GroupPeopleId = @"GroupPeopleId";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
