using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetCMS.DataAccess
{
    /// <summary>
    /// Controller class for Login
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class LoginController
    {
        // Preload our schema..
        Login thisSchemaLoad = new Login();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public LoginCollection FetchAll()
        {
            LoginCollection coll = new LoginCollection();
            Query qry = new Query(Login.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public LoginCollection FetchByID(object Id)
        {
            LoginCollection coll = new LoginCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public LoginCollection FetchByQuery(Query qry)
        {
            LoginCollection coll = new LoginCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (Login.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (Login.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int UserId,Guid Token,DateTime? DateLogin,bool? IsLogout)
	    {
		    Login item = new Login();
		    
            item.UserId = UserId;
            
            item.Token = Token;
            
            item.DateLogin = DateLogin;
            
            item.IsLogout = IsLogout;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int UserId,Guid Token,DateTime? DateLogin,bool? IsLogout)
	    {
		    Login item = new Login();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.UserId = UserId;
				
			item.Token = Token;
				
			item.DateLogin = DateLogin;
				
			item.IsLogout = IsLogout;
				
	        item.Save(UserName);
	    }
    }
}
